package kiwi.ingenuity.netbeans.plugin.aicoder.ai.idlewatch;

import java.time.Duration;
import java.time.Instant;

/**
 * A single armed idle-watch subscription: session {@code watcherSessionId} waits for session {@code targetSessionId} to
 * have been continuously idle for {@code timeout}, at which point the watcher is notified. One-shot subscriptions are
 * removed once they fire (or are cancelled); recurring ones fire at most once per idle period and re-arm automatically.
 * When {@code interrupt} is true the notice is delivered with a graceful interrupt request (like an important message)
 * so a busy watcher session is woken to read it; the default {@code false} defers the notice until its next turn end.
 * <p>
 * Ids are generated by {@link IdleWatcherRegistry} as {@code idle-watch-N}, counting up from 1.
 */
public record IdleWatcher(String id, String watcherSessionId, String targetSessionId, Duration timeout,
                          boolean recurring, boolean interrupt, String note, Instant createdAt) {

}
