package kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.McpToolEnum;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.server.McpHookServer;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ai.DeleteAiMessageTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ai.GetAiMessagesTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ai.IsAiSessionActiveTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ai.ListAiSessionsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ai.ReadAiMessageTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ai.SendAiMessageTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ai.UpdateSessionDescriptionTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.build.BuildAntProjectTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.build.BuildGradleProjectTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.build.BuildMavenProjectTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.build.CleanAndBuildMavenProjectTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.build.DownloadMavenJavadocTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.build.DownloadMavenSourcesTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.test.RunAntTestsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.test.RunGradleTestsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.devops.test.RunMavenTestsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GetGitDiffTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GetGitStatusTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitAddTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitBlameTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitBranchTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitCheckoutTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitCherryPickTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitCommitTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitDeleteBranchTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitFetchTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitLogTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitMergeTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitPullTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitPushTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitRebaseTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitRemoteTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitResetTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitRevertTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitShowTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitStashTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.git.GitTagTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.help.GetClassMembersTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.help.GetJavadocTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.help.GetProjectStructureTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.help.GetTypeHierarchyTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.plugin.GetInstructionsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.plugin.GetPluginVersionTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.refactor.ChangeMethodSignatureTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.refactor.InlineVariableTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.refactor.MoveClassTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.refactor.RenameSymbolTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.search.FindDeclarationTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.search.FindImplementationsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.search.FindUsagesTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.search.SearchInFilesTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.search.SearchSymbolsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.search.SearchTypesTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.system.CopyFileTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.system.DeleteFileTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.system.GetClipboardTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.system.GetFileContentTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.system.MoveFileTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.system.RefreshFileStatusTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.system.SaveFileTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.build.BuildProjectTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.build.CleanAndBuildProjectTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.build.CleanProjectTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.diag.RunInspectTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.file.CloseFileTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.file.GetCurrentFileContentTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.file.GetCurrentFileTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.file.GetDiagnosticsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.file.GetOpenFilesTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.file.GetSelectedTextTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.navigate.NavigateToLineTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.source.FixImportsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.source.OrganiseImportsTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.source.OrganiseMembersTool;
import kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.ui.source.ReformatFileTool;

public final class ToolHandlerFactory {

    private ToolHandlerFactory() {
    }

    public static Map<McpToolEnum, McpToolInterface> getToolHandlers(McpHookServer server) {
        Map<McpToolEnum, McpToolInterface> map = new LinkedHashMap<>();
        map.put(McpToolEnum.FIND_USAGES, new FindUsagesTool());
        map.put(McpToolEnum.GET_DIAGNOSTICS, new GetDiagnosticsTool());
        map.put(McpToolEnum.GET_SELECTED_TEXT, new GetSelectedTextTool());
        map.put(McpToolEnum.GET_CURRENT_FILE, new GetCurrentFileTool());
        map.put(McpToolEnum.GET_OPEN_FILES, new GetOpenFilesTool());
        map.put(McpToolEnum.GET_CLIPBOARD, new GetClipboardTool());
        map.put(McpToolEnum.GET_CLASS_MEMBERS, new GetClassMembersTool());
        map.put(McpToolEnum.GET_TYPE_HIERARCHY, new GetTypeHierarchyTool());
        map.put(McpToolEnum.GET_CURRENT_FILE_CONTENT, new GetCurrentFileContentTool());
        map.put(McpToolEnum.GET_FILE_CONTENT, new GetFileContentTool(server));
        map.put(McpToolEnum.NAVIGATE_TO_LINE, new NavigateToLineTool());
        map.put(McpToolEnum.GET_PROJECT_STRUCTURE, new GetProjectStructureTool());
        map.put(McpToolEnum.BUILD_MAVEN_PROJECT, new BuildMavenProjectTool());
        map.put(McpToolEnum.CLEAN_AND_BUILD_MAVEN_PROJECT, new CleanAndBuildMavenProjectTool());
        map.put(McpToolEnum.CLEAN_PROJECT, new CleanProjectTool());
        map.put(McpToolEnum.BUILD_PROJECT, new BuildProjectTool());
        map.put(McpToolEnum.CLEAN_AND_BUILD_PROJECT, new CleanAndBuildProjectTool());
        map.put(McpToolEnum.RUN_MAVEN_TESTS, new RunMavenTestsTool());
        map.put(McpToolEnum.GET_GIT_STATUS, new GetGitStatusTool());
        map.put(McpToolEnum.GET_GIT_DIFF, new GetGitDiffTool());
        map.put(McpToolEnum.GIT_ADD, new GitAddTool());
        map.put(McpToolEnum.GIT_COMMIT, new GitCommitTool());
        map.put(McpToolEnum.GIT_LOG, new GitLogTool());
        map.put(McpToolEnum.GIT_PUSH, new GitPushTool());
        map.put(McpToolEnum.GIT_PULL, new GitPullTool());
        map.put(McpToolEnum.GIT_CHECKOUT, new GitCheckoutTool());
        map.put(McpToolEnum.GIT_BRANCH, new GitBranchTool());
        map.put(McpToolEnum.GIT_DELETE_BRANCH, new GitDeleteBranchTool());
        map.put(McpToolEnum.GIT_STASH, new GitStashTool());
        map.put(McpToolEnum.GIT_FETCH, new GitFetchTool());
        map.put(McpToolEnum.GIT_RESET, new GitResetTool());
        map.put(McpToolEnum.GIT_MERGE, new GitMergeTool());
        map.put(McpToolEnum.GIT_SHOW, new GitShowTool());
        map.put(McpToolEnum.GIT_BLAME, new GitBlameTool());
        map.put(McpToolEnum.GIT_REBASE, new GitRebaseTool());
        map.put(McpToolEnum.GIT_CHERRY_PICK, new GitCherryPickTool());
        map.put(McpToolEnum.GIT_TAG, new GitTagTool());
        map.put(McpToolEnum.GIT_REMOTE, new GitRemoteTool());
        map.put(McpToolEnum.GIT_REVERT, new GitRevertTool());
        map.put(McpToolEnum.REFRESH_NB_FILE_STATUS, new RefreshFileStatusTool());
        map.put(McpToolEnum.RENAME_SYMBOL, new RenameSymbolTool());
        map.put(McpToolEnum.MOVE_CLASS, new MoveClassTool());
        map.put(McpToolEnum.INLINE_VARIABLE, new InlineVariableTool());
        map.put(McpToolEnum.CHANGE_METHOD_SIGNATURE, new ChangeMethodSignatureTool());
        map.put(McpToolEnum.SEARCH_IN_FILES, new SearchInFilesTool());
        map.put(McpToolEnum.SEARCH_TYPES, new SearchTypesTool());
        map.put(McpToolEnum.SEARCH_SYMBOLS, new SearchSymbolsTool());
        map.put(McpToolEnum.FIND_DECLARATION, new FindDeclarationTool());
        map.put(McpToolEnum.FIND_IMPLEMENTATIONS, new FindImplementationsTool());
        map.put(McpToolEnum.FIX_IMPORTS, new FixImportsTool());
        map.put(McpToolEnum.ORGANISE_IMPORTS, new OrganiseImportsTool());
        map.put(McpToolEnum.RUN_INSPECT, new RunInspectTool());
        map.put(McpToolEnum.ORGANISE_MEMBERS, new OrganiseMembersTool());
        map.put(McpToolEnum.REFORMAT_FILE, new ReformatFileTool());
        map.put(McpToolEnum.SAVE_FILE, new SaveFileTool(server));
        map.put(McpToolEnum.APPLY_EDIT, new kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.files.ApplyEditTool());
        map.put(McpToolEnum.WRITE_FILE, new kiwi.ingenuity.netbeans.plugin.aicoder.process.tools.mcp.files.WriteFileTool());
        map.put(McpToolEnum.DELETE_FILE, new DeleteFileTool(server));
        map.put(McpToolEnum.COPY_FILE, new CopyFileTool(server));
        map.put(McpToolEnum.MOVE_FILE, new MoveFileTool(server));
        map.put(McpToolEnum.CLOSE_FILE, new CloseFileTool());
        map.put(McpToolEnum.GET_PLUGIN_VERSION, new GetPluginVersionTool());
        map.put(McpToolEnum.GET_INSTRUCTIONS, new GetInstructionsTool());
        map.put(McpToolEnum.DOWNLOAD_MAVEN_SOURCES, new DownloadMavenSourcesTool());
        map.put(McpToolEnum.DOWNLOAD_MAVEN_JAVADOC, new DownloadMavenJavadocTool());
        map.put(McpToolEnum.BUILD_GRADLE_PROJECT, new BuildGradleProjectTool());
        map.put(McpToolEnum.RUN_GRADLE_TESTS, new RunGradleTestsTool());
        map.put(McpToolEnum.BUILD_ANT_PROJECT, new BuildAntProjectTool());
        map.put(McpToolEnum.RUN_ANT_TESTS, new RunAntTestsTool());
        map.put(McpToolEnum.GET_JAVADOC, new GetJavadocTool());
        map.put(McpToolEnum.LIST_AI_SESSIONS, new ListAiSessionsTool());
        map.put(McpToolEnum.SEND_AI_MESSAGE, new SendAiMessageTool());
        map.put(McpToolEnum.GET_AI_MESSAGES, new GetAiMessagesTool());
        map.put(McpToolEnum.READ_AI_MESSAGE, new ReadAiMessageTool());
        map.put(McpToolEnum.DELETE_AI_MESSAGE, new DeleteAiMessageTool());
        map.put(McpToolEnum.IS_AI_SESSION_ACTIVE, new IsAiSessionActiveTool());
        map.put(McpToolEnum.UPDATE_SESSION_DESCRIPTION, new UpdateSessionDescriptionTool());
        return Collections.unmodifiableMap(map);
    }
}
